// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMeO3Nm4ExcbSWElAVICrlKCc4ZufFdgk',
    appId: '1:727243261368:web:25bdd96f905d1bf20d7b4d',
    messagingSenderId: '727243261368',
    projectId: 'clinic-app-b2569',
    authDomain: 'clinic-app-b2569.firebaseapp.com',
    storageBucket: 'clinic-app-b2569.firebasestorage.app',
    measurementId: 'G-0BWZPHHCEY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVgZVOeZxBClveR5vQ-tCha8D99vFGkU8',
    appId: '1:727243261368:android:f881fc8b61ded5550d7b4d',
    messagingSenderId: '727243261368',
    projectId: 'clinic-app-b2569',
    storageBucket: 'clinic-app-b2569.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf2WlWELXh5LjWQcfOlEcc0VZQOekmSWo',
    appId: '1:727243261368:ios:c50bb655a7983d1b0d7b4d',
    messagingSenderId: '727243261368',
    projectId: 'clinic-app-b2569',
    storageBucket: 'clinic-app-b2569.firebasestorage.app',
    iosBundleId: 'com.example.clinicApp',
  );

}